### ISSUE TITLE
problem to replicate reynolds stress R12 if I change the sigma profile Reynold stress profile

### ISSUE THREAD

**Issue by pandac55** [kaschau/sempy#1]
Hello, I am Sunce. I have resolved the issue I previously emailed you about, which was caused by not adjusting the scale ratio simultaneously when enlarging delta. However, I have now encountered a new problem. I tried replacing the sigma profile and Reynolds profile in the example you provided with data from my experiment. But the results show that the simulation outcomes for u'v' did not meet our expectations, and currently, we have not identified the source of the problem. In the attachment, we have included our experimental data and scripts, hoping you can provide relevant suggestions. Thank you! I look forward to your reply.
[sempy-main.zip](https://github.com/kaschau/sempy/files/14532026/sempy-main.zip)

**Comment by kaschau** [comment]
Hi Sunce,

R12 is the most difficult Reynolds stress to replicate exactly. If you take a look at the examples, they will often not perform for the off-diagonal stresses as well as the diagonal components. This is due to the fact that, like the original SEM, the ESEM still relies on randomness to APPROXIMATE zero covariance between the un-normalized u', v', and w'  signals. Thus, increasing the number of eddies, or increasing the length of the ensemble signal should help.

Alternatively, you can verify this by "whitening" the un-normalized signal to enforce perfect de-correlation between u', v', and w' regardless of the ensemble duration or number of eddies. This functionality is already in the code, commented out in the [exact normalization routine here](https://github.com/kaschau/sempy/blob/f2055938e1e4f09f4a26384ce7203f15a572679b/sempy/normalization/exactNorm.py#L26).

If you uncomment this block and use the ```'exact'``` normalization, you will see perfect statistics everywhere, to within machine precision. However, as mentioned in the paper, this can have detrimental effects on the spatial coherence within the plane of your inlet. So we just chose to take a lack of performance in the R12 statistics matching, as they were still very small compared to the diagonal values in most cases, and matched good enough in our tests.

**Comment by kaschau** [comment]
Here is an example of using the whitening procedure versus not. While I do not know the exact cause, I am fairly certain the solution of the eigenvalue problem in the whitening procedure becomes ill conditioned, and causes these sharp transition from positive to negative in certain areas of the flow field.

![985cdf00-a4f8-11eb-8ef5-48ad94f6abed](https://github.com/kaschau/sempy/assets/46926848/5bc116d1-8be8-4982-b4eb-d71360bf3dab)
![c2ae9c80-a4f8-11eb-95aa-5608658cf4fc](https://github.com/kaschau/sempy/assets/46926848/83ca07a1-d3ba-4a1a-9378-15118fc5ed8f)

**Comment by pandac55** [comment]
Thank you very much for your patient reply. We will consider your suggestions and think about how to further improve this issue. If I have new ideas, I may connect you again. Once again, I express my gratitude.
